export type Contractor = {
  id: string;
  name: string;
  specialty: { DE: string; EN: string };
  specialtyKey: string; // for filtering / matching
  rating: number;
  reviews: number;
  etaHours: number;
  available: boolean;
  city: string;
  serviceArea: string[];
  priceRange: string;
  topMatch?: boolean;
  preferred?: boolean;
  phone: string;
  email: string;
  activeJobs: number;
  pastJobs: number;
  avgCompletionHours: number;
  reliability: number; // 0-100
  aiReason: { DE: string; EN: string };
};

const bi = (de: string, en: string) => ({ DE: de, EN: en });

export const allContractors: Contractor[] = [
  {
    id: "c1",
    name: "Müller Heizung GmbH",
    specialty: bi("Heizungsnotdienst", "Emergency heating service"),
    specialtyKey: "Heating",
    rating: 4.9,
    reviews: 312,
    etaHours: 2,
    available: true,
    city: "Berlin",
    serviceArea: ["Berlin", "Potsdam"],
    priceRange: "€€",
    topMatch: true,
    preferred: true,
    phone: "+49 30 555 1110",
    email: "dispatch@mueller-heizung.de",
    activeJobs: 3,
    pastJobs: 184,
    avgCompletionHours: 6,
    reliability: 97,
    aiReason: bi(
      "Beste Reaktionszeit (Ø 2 Std.) für Heizungs-Notfälle in Berlin, 184 abgeschlossene Aufträge ohne Eskalation.",
      "Best response time (avg. 2 h) for heating emergencies in Berlin, 184 jobs completed without escalation.",
    ),
  },
  {
    id: "c2",
    name: "Therm-Service Berlin",
    specialty: bi("Heizung & Sanitär", "Heating & sanitary"),
    specialtyKey: "Heating",
    rating: 4.6,
    reviews: 178,
    etaHours: 4,
    available: true,
    city: "Berlin",
    serviceArea: ["Berlin"],
    priceRange: "€€",
    phone: "+49 30 555 2210",
    email: "buero@therm-service.de",
    activeJobs: 1,
    pastJobs: 96,
    avgCompletionHours: 9,
    reliability: 91,
    aiReason: bi("Solide Alternative bei Auslastung von Müller.", "Solid backup when Müller is busy."),
  },
  {
    id: "c4",
    name: "Klempner Schulz & Söhne",
    specialty: bi("Klempner & Sanitär", "Plumbing & sanitary"),
    specialtyKey: "Plumber",
    rating: 4.8,
    reviews: 244,
    etaHours: 1,
    available: true,
    city: "München",
    serviceArea: ["München", "Augsburg"],
    priceRange: "€€",
    topMatch: true,
    preferred: true,
    phone: "+49 89 555 3320",
    email: "termin@schulz-klempner.de",
    activeJobs: 2,
    pastJobs: 221,
    avgCompletionHours: 4,
    reliability: 96,
    aiReason: bi(
      "Top Bewertung in München, Spezialist für Leitungs- und Siphonprobleme.",
      "Top rating in Munich, specialist in pipe and siphon issues.",
    ),
  },
  {
    id: "c5",
    name: "AquaStop München",
    specialty: bi("Wasserschäden", "Water damage"),
    specialtyKey: "Plumber",
    rating: 4.5,
    reviews: 132,
    etaHours: 3,
    available: true,
    city: "München",
    serviceArea: ["München"],
    priceRange: "€€€",
    phone: "+49 89 555 4430",
    email: "notruf@aquastop.de",
    activeJobs: 4,
    pastJobs: 78,
    avgCompletionHours: 12,
    reliability: 89,
    aiReason: bi("Bei größeren Wasserschäden mit Trocknung empfohlen.", "Recommended for larger water damage requiring drying."),
  },
  {
    id: "c3",
    name: "Elektro Bauer",
    specialty: bi("Elektroinstallation", "Electrical installation"),
    specialtyKey: "Electrician",
    rating: 4.7,
    reviews: 201,
    etaHours: 5,
    available: true,
    city: "Frankfurt",
    serviceArea: ["Frankfurt", "Offenbach"],
    priceRange: "€€",
    preferred: true,
    topMatch: true,
    phone: "+49 69 555 6610",
    email: "service@elektro-bauer.de",
    activeJobs: 2,
    pastJobs: 152,
    avgCompletionHours: 8,
    reliability: 94,
    aiReason: bi(
      "Hauptpartner für Elektrik in Frankfurt, geringe Rückläuferquote.",
      "Main electrical partner in Frankfurt, very low callback rate.",
    ),
  },
  {
    id: "c6",
    name: "Vodafone Business Support",
    specialty: bi("Anbieterstörung", "Provider support"),
    specialtyKey: "Internet",
    rating: 4.1,
    reviews: 1820,
    etaHours: 24,
    available: true,
    city: "Remote",
    serviceArea: ["Remote"],
    priceRange: "—",
    topMatch: true,
    phone: "+49 800 555 0001",
    email: "business@vodafone.de",
    activeJobs: 6,
    pastJobs: 412,
    avgCompletionHours: 22,
    reliability: 82,
    aiReason: bi("Direkter Provider-Kanal – schneller als Web-Ticket.", "Direct provider line — faster than the web ticket form."),
  },
  {
    id: "c7",
    name: "NetTech Köln",
    specialty: bi("Netzwerk vor Ort", "On-site networking"),
    specialtyKey: "Internet",
    rating: 4.6,
    reviews: 88,
    etaHours: 8,
    available: false,
    city: "Köln",
    serviceArea: ["Köln", "Bonn"],
    priceRange: "€€",
    phone: "+49 221 555 7720",
    email: "hilfe@nettech-koeln.de",
    activeJobs: 0,
    pastJobs: 41,
    avgCompletionHours: 11,
    reliability: 88,
    aiReason: bi("Vor-Ort-Diagnose, wenn Provider nichts findet.", "On-site diagnosis when the provider can't find a fault."),
  },
  {
    id: "c8",
    name: "Schindler Service",
    specialty: bi("Aufzugswartung", "Elevator maintenance"),
    specialtyKey: "Elevator",
    rating: 4.7,
    reviews: 530,
    etaHours: 5,
    available: true,
    city: "Hamburg",
    serviceArea: ["Hamburg", "Bremen", "Lübeck"],
    priceRange: "€€€",
    topMatch: true,
    preferred: true,
    phone: "+49 40 555 8840",
    email: "service.de@schindler.com",
    activeJobs: 5,
    pastJobs: 318,
    avgCompletionHours: 18,
    reliability: 95,
    aiReason: bi("Vertragspartner für Aufzüge mit garantiertem 24h-SLA.", "Contracted elevator partner with a guaranteed 24 h SLA."),
  },
  {
    id: "c9",
    name: "Gutachter Bauer",
    specialty: bi("Schimmelgutachten", "Mould assessment"),
    specialtyKey: "Mold",
    rating: 4.8,
    reviews: 64,
    etaHours: 48,
    available: true,
    city: "Leipzig",
    serviceArea: ["Leipzig", "Halle"],
    priceRange: "€€€",
    topMatch: true,
    phone: "+49 341 555 9900",
    email: "kontakt@gutachter-bauer.de",
    activeJobs: 1,
    pastJobs: 37,
    avgCompletionHours: 72,
    reliability: 93,
    aiReason: bi("Zertifizierte:r Bausachverständige:r für Feuchteanalysen.", "Certified surveyor for moisture analysis."),
  },
  {
    id: "c10",
    name: "Hausmeister Krüger",
    specialty: bi("Hausmeisterservice", "Caretaker services"),
    specialtyKey: "Cleaning",
    rating: 4.9,
    reviews: 412,
    etaHours: 4,
    available: true,
    city: "Berlin",
    serviceArea: ["Berlin"],
    priceRange: "€",
    preferred: true,
    phone: "+49 30 555 1230",
    email: "krueger@hausmeisterservice.de",
    activeJobs: 7,
    pastJobs: 612,
    avgCompletionHours: 3,
    reliability: 99,
    aiReason: bi("Erledigt Kleinaufträge am selben Tag.", "Handles small jobs the same day."),
  },
  {
    id: "c11",
    name: "Notdienst 24 Berlin",
    specialty: bi("Notreparaturen 24/7", "24/7 emergency repair"),
    specialtyKey: "Emergency",
    rating: 4.3,
    reviews: 220,
    etaHours: 1,
    available: true,
    city: "Berlin",
    serviceArea: ["Berlin", "Potsdam"],
    priceRange: "€€€",
    phone: "+49 30 555 0000",
    email: "einsatz@notdienst24.de",
    activeJobs: 2,
    pastJobs: 188,
    avgCompletionHours: 4,
    reliability: 87,
    aiReason: bi("Letzte Option für nächtliche Notfälle.", "Last-resort partner for night-time emergencies."),
  },
  {
    id: "c12",
    name: "Glanz Reinigung GmbH",
    specialty: bi("Treppenhaus- & Gewerbereinigung", "Stairwell & commercial cleaning"),
    specialtyKey: "Cleaning",
    rating: 4.6,
    reviews: 145,
    etaHours: 12,
    available: true,
    city: "Köln",
    serviceArea: ["Köln", "Düsseldorf"],
    priceRange: "€",
    preferred: true,
    phone: "+49 221 555 4000",
    email: "kunden@glanz-reinigung.de",
    activeJobs: 3,
    pastJobs: 274,
    avgCompletionHours: 6,
    reliability: 96,
    aiReason: bi("Regelmäßiger Wartungspartner für mehrere Objekte.", "Recurring maintenance partner across multiple buildings."),
  },
];

// Legacy export kept for AssignContractorModal (grouped by ticket categoryKey)
export const contractors: Record<string, Contractor[]> = {
  Heating: allContractors.filter((c) => c.specialtyKey === "Heating"),
  "Water leak": allContractors.filter((c) => c.specialtyKey === "Plumber"),
  Internet: allContractors.filter((c) => c.specialtyKey === "Internet"),
  Elevator: allContractors.filter((c) => c.specialtyKey === "Elevator"),
  Mold: allContractors.filter((c) => c.specialtyKey === "Mold"),
  Lighting: allContractors.filter((c) => c.specialtyKey === "Cleaning" && c.id === "c10"),
  Electrical: allContractors.filter((c) => c.specialtyKey === "Electrician"),
};

export function getContractor(id: string) {
  return allContractors.find((c) => c.id === id) ?? allContractors[0];
}

export const insights = {
  resolutionTrend: [42, 38, 35, 33, 28, 24, 22, 19, 18, 15, 14, 12],
  volumeByCategory: [
    { label: { DE: "Heizung", EN: "Heating" }, value: 34, color: "bg-destructive" },
    { label: { DE: "Wasser", EN: "Water" }, value: 22, color: "bg-info" },
    { label: { DE: "Elektrik", EN: "Electrical" }, value: 14, color: "bg-warning" },
    { label: { DE: "Internet", EN: "Internet" }, value: 11, color: "bg-primary" },
    { label: { DE: "Aufzug", EN: "Elevator" }, value: 7, color: "bg-ai" },
    { label: { DE: "Sonstiges", EN: "Other" }, value: 12, color: "bg-muted-foreground" },
  ],
  automationRate: 68,
  avgResolutionHours: 14,
  slaBreaches: 3,
  responseTrend: [22, 19, 16, 14, 12, 11, 12, 10, 9, 11, 10, 8],
  atRisk: [
    { id: "VLT-2030", title: { DE: "Schimmel im Schlafzimmer", EN: "Mould in bedroom" }, hours: 36, reason: { DE: "Wartet auf Gutachter > 24 Std.", EN: "Awaiting surveyor > 24 h" } },
    { id: "VLT-2018", title: { DE: "Fenster undicht", EN: "Leaking window" }, hours: 52, reason: { DE: "Keine Mieter-Antwort seit 2 Tagen", EN: "No tenant reply in 2 days" } },
    { id: "VLT-2009", title: { DE: "Sprechanlage defekt", EN: "Intercom broken" }, hours: 71, reason: { DE: "SLA überschritten", EN: "SLA exceeded" } },
  ],
};
