/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ContractorsRouteImport } from './routes/contractors'
import { Route as ContractorRouteImport } from './routes/contractor'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketIdRouteImport } from './routes/ticket.$id'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as ContractorsIdRouteImport } from './routes/contractors.$id'
import { Route as OwnerIssuesRouteImport } from './routes/owner.issues'
import { Route as OwnerFinancialsRouteImport } from './routes/owner.financials'
import { Route as OwnerApprovalsRouteImport } from './routes/owner.approvals'
import { Route as ContractorScheduleRouteImport } from './routes/contractor.schedule'
import { Route as ContractorMessagesRouteImport } from './routes/contractor.messages'
import { Route as ContractorCompletedRouteImport } from './routes/contractor.completed'

const PropertiesRoute = PropertiesRouteImport.update({ id: '/properties', path: '/properties', getParentRoute: () => rootRouteImport } as any)
const PortalRoute = PortalRouteImport.update({ id: '/portal', path: '/portal', getParentRoute: () => rootRouteImport } as any)
const OwnerRoute = OwnerRouteImport.update({ id: '/owner', path: '/owner', getParentRoute: () => rootRouteImport } as any)
const IntakeRoute = IntakeRouteImport.update({ id: '/intake', path: '/intake', getParentRoute: () => rootRouteImport } as any)
const InsightsRoute = InsightsRouteImport.update({ id: '/insights', path: '/insights', getParentRoute: () => rootRouteImport } as any)
const InboxRoute = InboxRouteImport.update({ id: '/inbox', path: '/inbox', getParentRoute: () => rootRouteImport } as any)
const ContractorsRoute = ContractorsRouteImport.update({ id: '/contractors', path: '/contractors', getParentRoute: () => rootRouteImport } as any)
const ContractorRoute = ContractorRouteImport.update({ id: '/contractor', path: '/contractor', getParentRoute: () => rootRouteImport } as any)
const TenantRoute = TenantRouteImport.update({ id: '/tenant', path: '/tenant', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const TicketIdRoute = TicketIdRouteImport.update({ id: '/ticket/$id', path: '/ticket/$id', getParentRoute: () => rootRouteImport } as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({ id: '/$id', path: '/$id', getParentRoute: () => PropertiesRoute } as any)
const ContractorsIdRoute = ContractorsIdRouteImport.update({ id: '/$id', path: '/$id', getParentRoute: () => ContractorsRoute } as any)
const OwnerIssuesRoute = OwnerIssuesRouteImport.update({ id: '/issues', path: '/issues', getParentRoute: () => OwnerRoute } as any)
const OwnerFinancialsRoute = OwnerFinancialsRouteImport.update({ id: '/financials', path: '/financials', getParentRoute: () => OwnerRoute } as any)
const OwnerApprovalsRoute = OwnerApprovalsRouteImport.update({ id: '/approvals', path: '/approvals', getParentRoute: () => OwnerRoute } as any)
const ContractorScheduleRoute = ContractorScheduleRouteImport.update({ id: '/schedule', path: '/schedule', getParentRoute: () => ContractorRoute } as any)
const ContractorMessagesRoute = ContractorMessagesRouteImport.update({ id: '/messages', path: '/messages', getParentRoute: () => ContractorRoute } as any)
const ContractorCompletedRoute = ContractorCompletedRouteImport.update({ id: '/completed', path: '/completed', getParentRoute: () => ContractorRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tenant': typeof TenantRoute
  '/contractor': typeof ContractorRouteWithChildren
  '/contractors': typeof ContractorsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/intake': typeof IntakeRoute
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/contractor/schedule': typeof ContractorScheduleRoute
  '/contractor/messages': typeof ContractorMessagesRoute
  '/contractor/completed': typeof ContractorCompletedRoute
  '/contractors/$id': typeof ContractorsIdRoute
  '/owner/issues': typeof OwnerIssuesRoute
  '/owner/financials': typeof OwnerFinancialsRoute
  '/owner/approvals': typeof OwnerApprovalsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tenant': typeof TenantRoute
  '/contractor': typeof ContractorRouteWithChildren
  '/contractors': typeof ContractorsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/intake': typeof IntakeRoute
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/contractor/schedule': typeof ContractorScheduleRoute
  '/contractor/messages': typeof ContractorMessagesRoute
  '/contractor/completed': typeof ContractorCompletedRoute
  '/contractors/$id': typeof ContractorsIdRoute
  '/owner/issues': typeof OwnerIssuesRoute
  '/owner/financials': typeof OwnerFinancialsRoute
  '/owner/approvals': typeof OwnerApprovalsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tenant'
    | '/contractor'
    | '/contractors'
    | '/inbox'
    | '/insights'
    | '/intake'
    | '/owner'
    | '/portal'
    | '/properties'
    | '/contractor/schedule'
    | '/contractor/messages'
    | '/contractor/completed'
    | '/contractors/$id'
    | '/owner/issues'
    | '/owner/financials'
    | '/owner/approvals'
    | '/properties/$id'
    | '/ticket/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tenant'
    | '/contractor'
    | '/contractors'
    | '/inbox'
    | '/insights'
    | '/intake'
    | '/owner'
    | '/portal'
    | '/properties'
    | '/contractor/schedule'
    | '/contractor/messages'
    | '/contractor/completed'
    | '/contractors/$id'
    | '/owner/issues'
    | '/owner/financials'
    | '/owner/approvals'
    | '/properties/$id'
    | '/ticket/$id'
  id:
    | '__root__'
    | '/'
    | '/tenant'
    | '/contractor'
    | '/contractors'
    | '/inbox'
    | '/insights'
    | '/intake'
    | '/owner'
    | '/portal'
    | '/properties'
    | '/contractor/schedule'
    | '/contractor/messages'
    | '/contractor/completed'
    | '/contractors/$id'
    | '/owner/issues'
    | '/owner/financials'
    | '/owner/approvals'
    | '/properties/$id'
    | '/ticket/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantRoute: typeof TenantRoute
  ContractorRoute: typeof ContractorRouteWithChildren
  ContractorsRoute: typeof ContractorsRouteWithChildren
  InboxRoute: typeof InboxRoute
  InsightsRoute: typeof InsightsRoute
  IntakeRoute: typeof IntakeRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  PortalRoute: typeof PortalRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  TicketIdRoute: typeof TicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/properties': { id: '/properties'; path: '/properties'; fullPath: '/properties'; preLoaderRoute: typeof PropertiesRouteImport; parentRoute: typeof rootRouteImport }
    '/portal': { id: '/portal'; path: '/portal'; fullPath: '/portal'; preLoaderRoute: typeof PortalRouteImport; parentRoute: typeof rootRouteImport }
    '/owner': { id: '/owner'; path: '/owner'; fullPath: '/owner'; preLoaderRoute: typeof OwnerRouteImport; parentRoute: typeof rootRouteImport }
    '/intake': { id: '/intake'; path: '/intake'; fullPath: '/intake'; preLoaderRoute: typeof IntakeRouteImport; parentRoute: typeof rootRouteImport }
    '/insights': { id: '/insights'; path: '/insights'; fullPath: '/insights'; preLoaderRoute: typeof InsightsRouteImport; parentRoute: typeof rootRouteImport }
    '/inbox': { id: '/inbox'; path: '/inbox'; fullPath: '/inbox'; preLoaderRoute: typeof InboxRouteImport; parentRoute: typeof rootRouteImport }
    '/contractors': { id: '/contractors'; path: '/contractors'; fullPath: '/contractors'; preLoaderRoute: typeof ContractorsRouteImport; parentRoute: typeof rootRouteImport }
    '/contractor': { id: '/contractor'; path: '/contractor'; fullPath: '/contractor'; preLoaderRoute: typeof ContractorRouteImport; parentRoute: typeof rootRouteImport }
    '/tenant': { id: '/tenant'; path: '/tenant'; fullPath: '/tenant'; preLoaderRoute: typeof TenantRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/ticket/$id': { id: '/ticket/$id'; path: '/ticket/$id'; fullPath: '/ticket/$id'; preLoaderRoute: typeof TicketIdRouteImport; parentRoute: typeof rootRouteImport }
    '/properties/$id': { id: '/properties/$id'; path: '/$id'; fullPath: '/properties/$id'; preLoaderRoute: typeof PropertiesIdRouteImport; parentRoute: typeof PropertiesRoute }
    '/contractors/$id': { id: '/contractors/$id'; path: '/$id'; fullPath: '/contractors/$id'; preLoaderRoute: typeof ContractorsIdRouteImport; parentRoute: typeof ContractorsRoute }
    '/owner/issues': { id: '/owner/issues'; path: '/issues'; fullPath: '/owner/issues'; preLoaderRoute: typeof OwnerIssuesRouteImport; parentRoute: typeof OwnerRoute }
    '/owner/financials': { id: '/owner/financials'; path: '/financials'; fullPath: '/owner/financials'; preLoaderRoute: typeof OwnerFinancialsRouteImport; parentRoute: typeof OwnerRoute }
    '/owner/approvals': { id: '/owner/approvals'; path: '/approvals'; fullPath: '/owner/approvals'; preLoaderRoute: typeof OwnerApprovalsRouteImport; parentRoute: typeof OwnerRoute }
    '/contractor/schedule': { id: '/contractor/schedule'; path: '/schedule'; fullPath: '/contractor/schedule'; preLoaderRoute: typeof ContractorScheduleRouteImport; parentRoute: typeof ContractorRoute }
    '/contractor/messages': { id: '/contractor/messages'; path: '/messages'; fullPath: '/contractor/messages'; preLoaderRoute: typeof ContractorMessagesRouteImport; parentRoute: typeof ContractorRoute }
    '/contractor/completed': { id: '/contractor/completed'; path: '/completed'; fullPath: '/contractor/completed'; preLoaderRoute: typeof ContractorCompletedRouteImport; parentRoute: typeof ContractorRoute }
  }
}

interface ContractorsRouteChildren { ContractorsIdRoute: typeof ContractorsIdRoute }
const ContractorsRouteChildren: ContractorsRouteChildren = { ContractorsIdRoute: ContractorsIdRoute }
const ContractorsRouteWithChildren = ContractorsRoute._addFileChildren(ContractorsRouteChildren)

interface PropertiesRouteChildren { PropertiesIdRoute: typeof PropertiesIdRoute }
const PropertiesRouteChildren: PropertiesRouteChildren = { PropertiesIdRoute: PropertiesIdRoute }
const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(PropertiesRouteChildren)

interface ContractorRouteChildren {
  ContractorScheduleRoute: typeof ContractorScheduleRoute
  ContractorMessagesRoute: typeof ContractorMessagesRoute
  ContractorCompletedRoute: typeof ContractorCompletedRoute
}
const ContractorRouteChildren: ContractorRouteChildren = {
  ContractorScheduleRoute,
  ContractorMessagesRoute,
  ContractorCompletedRoute,
}
const ContractorRouteWithChildren = ContractorRoute._addFileChildren(ContractorRouteChildren)

interface OwnerRouteChildren {
  OwnerIssuesRoute: typeof OwnerIssuesRoute
  OwnerFinancialsRoute: typeof OwnerFinancialsRoute
  OwnerApprovalsRoute: typeof OwnerApprovalsRoute
}
const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerIssuesRoute,
  OwnerFinancialsRoute,
  OwnerApprovalsRoute,
}
const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantRoute: TenantRoute,
  ContractorRoute: ContractorRouteWithChildren,
  ContractorsRoute: ContractorsRouteWithChildren,
  InboxRoute: InboxRoute,
  InsightsRoute: InsightsRoute,
  IntakeRoute: IntakeRoute,
  OwnerRoute: OwnerRouteWithChildren,
  PortalRoute: PortalRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  TicketIdRoute: TicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
